### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pawel54321** [dracir9/Blender-Involute-gear#2]
Hello,
I install and add to my blender, but I see error when I want add gear:

Python: Traceback (most recent call last):
  File "C:\Users\< my >\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\addon_Involute_Gear.py", line 395, in execute
    add_object(self, context)
  File "C:\Users\< my >\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\addon_Involute_Gear.py", line 228, in add_object
    mesh.from_pydata(verts, edges, faces)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy_types.py", line 531, in from_pydata
    self.polygons.foreach_set("vertices", vertex_indices)
TypeError: couldn't access the py sequence

location: <unknown location>:-1

----

Blender version; 3.1.2

I need other version?

**Comment by swtya** [comment]
Same error in Blender 3.6.1
It does work in 2.93.

It certainly will not work in the newer than Blender 4.2 as Add-ons are now called Extensions.
